name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential ninja-build cmake pkg-config git qt6-base-dev qt6-base-private-dev qt6-declarative-dev qt6-declarative-private-dev qt6-wayland-dev qt6-wayland-private-dev qt6-shadertools-dev qt6-tools-dev qt6-tools-dev-tools libxkbcommon-dev libwayland-dev wayland-protocols libegl1-mesa-dev libgbm-dev libdrm-dev libpipewire-0.3-dev libpam0g-dev libpolkit-agent-1-dev libpolkit-gobject-1-dev libglib2.0-dev libxcb1-dev libjemalloc-dev libcli11-dev

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DQS_BUILD_CRASH=OFF -DQS_BUILD_TESTS=OFF

      - name: Build
        run: cmake --build build -j$(nproc)
