name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            qt6-base-dev \
            qt6-declarative-dev \
            qt6-shadertools-dev \
            qt6-svg-dev qt6-wayland-dev libcli11-dev \
            libwayland-dev \
            wayland-protocols \
            libpipewire-0.3-dev \
            spirv-tools libxkbcommon-dev \

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCRASH_HANDLING=OFF

      - name: Build
        run: cmake --build build
